#!/bin/sh
# powernap action to shut down the system using `systemctl poweroff`

set -e

if [ "$1" = "true" ]
then
	systemctl poweroff
	
	if [ -n "$POWERNAP_PID" ]
	then
		kill -USR1 "$POWERNAP_PID"
	fi
elif [ "$1" = "false" ]
then
	# Do nothing
	true
else
	echo "Usage: $0 <true|false>" 2>&1
	exit 64 # EX_USAGE
fi
