#!/bin/sh
# powernap action to suspend the system using `systemctl suspend-then-hibernate`

set -e

if [ "$1" = "true" ]
then
	systemctl suspend-then-hibernate
	powernapctl suspending
elif [ "$1" = "false" ]
then
	# Do nothing
	true
else
	echo "Usage: $0 <true|false>" 2>&1
	exit 64 # EX_USAGE
fi
