#!/bin/sh
# powernap action to shut down the system using `shutdown -P now`

set -e

if [ "$1" = "true" ]
then
	shutdown -P now
	powernapctl suspending
elif [ "$1" = "false" ]
then
	# Do nothing
	true
else
	echo "Usage: $0 <true|false>" 2>&1
	exit 64 # EX_USAGE
fi
